Add files via upload
Tsalraavkaan/Advance-Cpp pull request #1
Opened 2020-10-09 12:03 UTC by Tsalraavkaan

2020-10-09 18:21 UTC, a-badin requested changes

2020-10-09 18:21 UTC, a-badin commented on Task1/lib/Descriptor.hpp
> +        Descriptor(const int);
explicit

2020-10-09 18:21 UTC, a-badin commented on Task1/src/Descriptor.cpp
> +            std::cerr << "Error in closing desciptor" << std::endl;
Исключение

2020-10-09 18:21 UTC, a-badin commented on Task1/src/Process.cpp
> +            std::cerr << "Error in creating pipe" << std::endl;
Закрыть все

2020-10-09 18:21 UTC, a-badin commented on Task1/src/Process.cpp
> +        proc_pid = fork();
постфикс, префикс

2020-10-09 18:21 UTC, a-badin commented on Task1/src/Process.cpp
> +            if (waitpid(proc_pid, nullptr, 0) < 0) {
кинуть сигнал SINGINT, SIGKILL

2020-10-09 18:21 UTC, a-badin commented on Task1/src/Process.cpp
> +    Process::~Process() noexcept {
noexcept неявно уже объявлен

2020-10-13 14:47 UTC, a-badin requested changes

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Descriptor.cpp
> +        if (this) {
Напишите сценарий как это работает

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Descriptor.cpp
> +            throw Task1::DescriptorError("Error in closing desciptor");
Даже если close ошибся, система все равно закроет дескриптор, поэтому fd_ нужно выставить в -1
Секция `Dealing with error returns from close()` в man close

2020-10-13 14:47 UTC, a-badin commented on Task1/lib/Process.hpp
> +        Process(const std::string &, std::vector<std::string> &);
мы это не обсуждали, но понятное дело что напрашивается const вектор

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Process.cpp
> +        res.push_back(const_cast<char*> (path.c_str()));
не делайте const_cast это опасно, сделайте себе копии и проблема исчезнет

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Descriptor.cpp
> +            close();
close может кинуть исключение, в этом случае ваша программа упадет

2020-10-13 14:47 UTC, a-badin commented on Task1/lib/Exceptions.hpp
> +        BaseException(const std::string &);
Можно внести конструктор базового класса через
```
using std::runtime_error::runtime_error;
```
Аналогично в ваших потомках:
```
using BaseException::BaseException;
```
Тогда файл реализации Exceptions.cpp будет вообще не нужен и библиотека тоже

2020-10-13 14:47 UTC, a-badin commented on Task1/example/parent.cpp
> +#include "../lib/Process.hpp"
такого быть не должно, правильно организуйте свой проект

2020-10-13 14:47 UTC, a-badin commented on Task1/lib/Descriptor.hpp
> +    class Descriptor {
Обычно сущности внутри namespace не отступаются

2020-10-13 14:47 UTC, a-badin commented on Task1/lib/Descriptor.hpp
> +}
Хорошим стилем считается закрывать пространство имен с комментарием вида `// namespace Task1 `

2020-10-13 14:47 UTC, a-badin commented on Task1/lib/Process.hpp
> +#include <unistd.h>
Чем меньше вы include'ите в заголовочном файле тем быстрее собирается ваш проект, оставьте только то, что необходимо для объявления

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Process.cpp
> +            return static_cast<ssize_t> (num_read);
size_t

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Process.cpp
> +            return static_cast<ssize_t> (num_written);
size_t

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Process.cpp
> +        ssize_t num_written = 0;
size_t

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Process.cpp
> +        ssize_t num_read = 0;
size_t

2020-10-13 14:47 UTC, a-badin commented on Task1/src/Process.cpp
> +        closeStdin();
Тут имелась ввиду логика повторения деструктора - отправка сигнала и завершение

2020-10-13 22:25 UTC, Tsalraavkaan commented on Task1/src/Descriptor.cpp
> +        if (this) {
ошибку понял, надо *this, чтобы вернулся объект и уже с помощью перегрузки оператора bool в условии происходила проверка fd_ != -1

2020-10-13 22:27 UTC, Tsalraavkaan commented on Task1/src/Process.cpp
> +        int pipe_in[2], pipe_out[2];
Из-за этого места и того, что ниже разбил условие на 2, чтобы избежать большой дубликации кода

2020-10-13 23:13 UTC, Tsalraavkaan commented on Task1/src/Descriptor.cpp
> +        if (this) {
А нет, это вообще не имеет смысла, так как эту проверку делает close()

2020-10-15 11:15 UTC, a-badin approved these changes
Можете не доправлять, если не успеваете

2020-10-15 11:15 UTC, a-badin commented on Task1/src/Descriptor.cpp
> +        exit(1);
вот это лишнее

2020-10-15 11:15 UTC, a-badin commented on Task1/src/Process.cpp
> +            exit(1);
Это тоже лишнее, в общем случае ваша программа падать не должна.

Плюс получается в деструкторе вы ловите исключение, но метод close() его не кидает - ловить то нечего

2020-10-15 11:18 UTC, merged