Первая версия программы
Tsalraavkaan/Advance-Cpp pull request #3
Opened 2020-10-20 22:42 UTC by Tsalraavkaan

Вроде бы все написано, но по крайней мере есть ошибка в коде сервера. Надеюсь до занятия успеть исправить

2020-10-23 19:56 UTC, Kapitonov requested changes

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Socket.cpp
> +}
Нет возвращаемого значения.

2020-10-23 19:56 UTC, Kapitonov commented on Task3/lib/Exceptions.hpp
> +class PipeError : public BaseException {
Лишний класс

2020-10-23 19:56 UTC, Kapitonov commented on Task3/lib/Exceptions.hpp
> +class ProcessError : public BaseException {
Лишний класс

2020-10-23 19:56 UTC, Kapitonov commented on Task3/lib/Descriptor.hpp
> +    int fd_;
Инициализировать невалидным значением.

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Connection.cpp
> +    connection.sock_fd_.set_fd(-1);
Лишнее.

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Connection.cpp
> +        ssize_t recived = read(static_cast<char*>(data) + num_read, len - num_read);
size_t

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Descriptor.cpp
> +Descriptor::Descriptor(Descriptor &&disc) : fd_{disc.fd_} {
desc

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Server.cpp
> +Server::Server() : sock_fd_{-1} {}
Дефолтный конструктор соккета и так ставит в -1 дексриптор.

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Server.cpp
> +    server.sock_fd_.set_fd(-1);
Не нужно

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Server.cpp
> +    int client_fd = ::accept(sock_fd_.get_fd(), reinterpret_cast<sockaddr*>(&client_addr), &addr_size);
Если не использовать адреса, то можно указать nullptr.

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Socket.cpp
> +Socket::Socket() : sock_fd_(-1) {}
Не надо передавать -1

2020-10-23 19:56 UTC, Kapitonov commented on Task3/src/Socket.cpp
> +    sock_fd_.set_fd(-1);
Что-то странное происходит

2020-10-23 20:21 UTC, Tsalraavkaan commented on Task3/lib/Descriptor.hpp
> +    int fd_;
Инициализируется в Descriptor::Descriptor()

2020-10-30 13:46 UTC, Kapitonov requested changes

2020-10-30 13:46 UTC, Kapitonov commented on Task3/src/Server.cpp
> +    sock_fd_.set_fd(std::move(server.sock_fd_));
А это точно корректный метод? Корректнее, наверное sock_fd_ = std::move(server.sock_fd_)

2020-11-03 16:11 UTC, Kapitonov requested changes

2020-11-03 16:11 UTC, Kapitonov commented on Task3/src/Server.cpp
> +    set_max_connection(max_connection);
Что со строгой безопасностью, если исклювение в методе set_max_connection?

2020-11-13 22:18 UTC, merged