Initial commit
Tsalraavkaan/Advance-Cpp pull request #5
Opened 2020-11-07 13:52 UTC by Tsalraavkaan

2020-11-10 19:48 UTC, a-badin requested changes

2020-11-10 19:48 UTC, a-badin commented on Task4/lib/SharedMap.hpp
> +        map_->operator[](convertKey(key)) = convertValue(value);
нужно получить элемент не создавая новый, если не найден

2020-11-10 20:05 UTC, Tsalraavkaan commented on Task4/lib/Semaphore.hpp
> +#include "Exceptions.hpp"
Изначально в местах с throw; в .cpp хотел позже добавить нормальные исключения, но потом забыл это сделать. Сейчас исправлю

2020-11-10 20:18 UTC, Tsalraavkaan commented on Task4/lib/SharedMap.hpp
> +    using map_unique_ptr = std::unique_ptr<char, std::function<void(char*)>>;
Нет, изначально хотел это использовать, но потом забыл убрать

2020-11-12 14:14 UTC, a-badin commented on Task4/lib/Semaphore.hpp
> +#include "Exceptions.hpp"
Ну для объявления класса Semaphore то они вам не нужны

2020-11-12 14:28 UTC, a-badin requested changes
Декструтор

2020-11-12 14:28 UTC, a-badin commented on Task4/example/client.cpp
> +        } catch (Tasks::KeyError err) {
Tasks::KeyError& err

2020-11-17 17:39 UTC, a-badin approved these changes

2020-11-17 17:39 UTC, a-badin commented on Task4/include/Semaphore.hpp
> +#include "Exceptions.hpp"
Ещё раз, для объявления класса исключения не нужны

2020-11-17 17:39 UTC, merged