First commit
Tsalraavkaan/Advance-Cpp pull request #6
Opened 2020-11-13 15:08 UTC by Tsalraavkaan

Клиент не присоединяется к сервису, требуется доработка

2020-11-20 19:04 UTC, Kapitonov requested changes

2020-11-20 19:04 UTC, Kapitonov commented on Task5/src/Service.cpp
> +                    size_t len = iter_client->get_connection().read(buf.data(), buf.size());
Можно реализовать внутри BufConnection

2020-11-20 19:04 UTC, Kapitonov commented on Task5/src/Service.cpp
> +                    std::string &write_buf = iter_client->get_write_buf();
По возможномти вынести в BufConnection

2020-11-20 19:04 UTC, Kapitonov commented on Task5/include/EPoll.hpp
> +    std::vector<::epoll_event> wait(int = 1000, int = 1024);
Вынести в константы.

2020-11-20 20:46 UTC, Tsalraavkaan commented
Указанные баги исправил, также удалил все лишние файлы

2020-11-20 21:36 UTC, Tsalraavkaan commented on Task5/src/Service.cpp
> +    epoll_.add(server_.get_fd(), EVENT_FLAG::RDW);
При попытке открыть соединение до закрытия предыдущего бросается исключение. При закрытиии же соединения(вызове метода close у Service) как раз происходит удаление дескриптора из епола

2020-11-27 19:47 UTC, Kapitonov requested changes
Остальное, вроде, нормально.

2020-11-27 19:47 UTC, Kapitonov commented on Task5/src/EPoll.cpp
> +    throw_epollerr(!epfd, "Error in creating epoll");
А тут точно все хорошо? Если epfd == -1, то не получим ошибки же.

2020-12-02 09:05 UTC, Tsalraavkaan commented on Task5/src/EPoll.cpp
> +    throw_epollerr(!epfd, "Error in creating epoll");
epfd имеет тип tcp::Descriptor, у которого переопределен operator bool, который возвращает fd != -1. Поэтому для проверки fd == -1 надо сделать !epfd

2020-12-04 14:59 UTC, merged